# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
#  - repo: https://github.com/scop/pre-commit-shfmt
#    rev: v3.8.0-1
#    hooks:
#      - id: shfmt
#        args: [--write, --indent, '4']
#  - repo: https://github.com/shellcheck-py/shellcheck-py
#    rev: v0.10.0.1
#    hooks:
#      - id: shellcheck
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
