unbind r
bind r source-file ~/.tmux.conf

set-option -g default-shell /bin/zsh
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

set -g base-index 1

set -g mouse on

set-window-option -g mode-keys vi
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Make the status line more pleasant.
set -g status-left ''
set -g status-right '#S '
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100


# Initialize TPM plugin manager
run '~/.tmux/plugins/tpm/tpm'
